name: Docker Image CI

on:
  pull_request:
    branches: ['main']
env:
  IMAGE_NAME: recipe-randomizer
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Test
        run: bun test
      - name: Check
        run: bun run check
      - name: Build
        run: bun run build
