name: Docker Image CI

on:
  pull_request:
    branches: ['main']
env:
  IMAGE_NAME: recipe-randomizer
  PUBLIC_DATA_ROOT: ./data
  RUNTIME_ENVIRONMENT: node
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm run test:unit
      - name: Check
        run: pnpm run check
      - name: Build
        run: pnpm run build
